export const USER_REGIS_SUCCESS = "USER_REGIS_SUCCESS";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const AUTH_SYSTEM_LOGIN_ERROR = "LOGIN_SYSTEM_ERROR";
export const AUTH_SYSTEM_REGIS_ERROR = "REGIS_SYSTEM_ERROR";
export const AUTH_LOADING = "AUTH_LOADING";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_MODAL_OPEN = "USER_MODAL_OPEN";
export const USER_MODAL_CLOSE = "USER_MODAL_CLOSE";

// ================================== admin manage product

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_DATAEDIT_SUCCESS = "GET_DATAEDIT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";
export const DELETE_PRODUCT_LOADING = "DELETE_PRODUCT_LOADING";
export const MODAL_DELETE = "MODAL_DELETE";
export const MODAL_ADD = "MODAL_ADD";

// ======================================== view detail

export const GET_VIEWDETAIL_FOOTBALL = "GET_VIEWDETAIL_FOOTBALL";
export const GET_VIEWDETAIL_BASKETBALL = "GET_VIEWDETAIL_BASKETBALL";
export const GET_VIEWDETAIL_RUNNING = "GET_VIEWDETAIL_RUNNING";
export const GET_VIEWDETAIL_LOADING = "GET_VIEWDETAIL_LOADING";
export const GET_VIEWDETAIL_ERROR = "GET_VIEWDETAIL_ERROR";

// =============================================== cart
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";
export const GET_CART_LOADING = "GET_CART_LOADING";
export const CART_DELETE_LOADING = "CART_DELETE_LOADING";
export const CART_DELETE_ERROR = "CART_DELETE_ERROR";

// =============================================== CheckOut
export const GET_CHECKOUT_SUCCESS = "GET_CHECKOUT_SUCCESS";
export const GET_CHECKOUT_ERROR = "GET_CHECKOUT_ERROR";
export const GET_CHECKOUT_LOADING = "GET_CHECKOUT_LOADING";
export const POST_CHECKOUT_SUCCESS = "POST_CHECKOUT_SUCCESS";
export const POST_CHECKOUT_ERROR = "POST_CHECKOUT_ERROR";
export const POST_CHECKOUT_LOADING = "POST_CHECKOUT_LOADING";
export const PUT_CHECKOUT_SUCCESS = "PUT_CHECKOUT_SUCCESS";
export const PUT_CHECKOUT_ERROR = "PUT_CHECKOUT_ERROR";
export const PUT_CHECKOUT_LOADING = "PUT_CHECKOUT_LOADING";

// ================================================== Home
export const GET_FOOTBALL_SUCCESS = "GET_FOOTBALL_SUCCESS";
export const GET_BASKETBALL_SUCCESS = "GET_BASKETBALL_SUCCESS";
export const GET_RUNNING_SUCCESS = "GET_RUNNING_SUCCESS";
export const GET_HOME_ERROR = "GET_HOME_ERROR";
export const GET_HOME_LOADING = "GET_HOME_LOADING";

// ==================================================== payment request
export const GET_PAYREQ_SUCCESS = "GET_PAYREQ_SUCCESS";
export const GET_PAYREQ_ERROR = "GET_PAYREQ_ERROR";
export const GET_PAYREQ_LOADING = "GET_PAYREQ_LOADING";
export const GET_EACH_SUCCESS = "GET_EACH_SUCCESS";
export const GET_EACH_ERROR = "GET_EACH_ERROR";
export const GET_EACH_LOADING = "GET_EACH_LOADING";
export const PUT_APPROVE_SUCCESS = "PUT_APPROVE_SUCCESS";
export const PUT_APPROVE_ERROR = "PUT_APPROVE_ERROR";
export const PUT_APPROVE_LOADING = "PUT_APPROVE_LOADING";

// ========================================================= account details
export const EDIT_DETAILS_SUCCESS = "EDIT_DETAILS_SUCCESS";
export const EDIT_DETAILS_ERROR = "EDIT_DETAILS_ERROR";
export const EDIT_DETAILS_LOADING = "EDIT_DETAILS_LOADING";
export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";
export const GET_DETAILS_ERROR = "GET_DETAILS_ERROR";
export const GET_DETAILS_LOADING = "GET_DETAILS_LOADING";
export const PASS_CHANGE_SUCCESS = "PASS_CHANGE_SUCCESS";
export const PASS_CHANGE_ERROR = "PASS_CHANGE_ERROR";
export const PASS_CHANGE_LOADING = "PASS_CHANGE_LOADING";
