export const USER_REGIS_SUCCESS = 'USER_REGIS_SUCCESS'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const AUTH_SYSTEM_LOGIN_ERROR = 'LOGIN_SYSTEM_ERROR'
export const AUTH_SYSTEM_REGIS_ERROR = 'REGIS_SYSTEM_ERROR'
export const AUTH_LOADING = 'AUTH_LOADING'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_MODAL_OPEN = 'USER_MODAL_OPEN'
export const USER_MODAL_CLOSE = 'USER_MODAL_CLOSE'

// ================================== admin manage product

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING'
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_DATAEDIT_SUCCESS = 'GET_DATAEDIT_SUCCESS'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'
export const DELETE_PRODUCT_LOADING = 'DELETE_PRODUCT_LOADING'
export const MODAL_DELETE = 'MODAL_DELETE'
export const MODAL_ADD='MODAL_ADD'

// ======================================== view detail

export const GET_VIEWDETAIL_FOOTBALL = 'GET_VIEWDETAIL_FOOTBALL'
export const GET_VIEWDETAIL_BASKETBALL = 'GET_VIEWDETAIL_BASKETBALL'
export const GET_VIEWDETAIL_RUNNING = 'GET_VIEWDETAIL_RUNNING'
export const GET_VIEWDETAIL_LOADING = 'GET_VIEWDETAIL_LOADING'
export const GET_VIEWDETAIL_ERROR = 'GET_VIEWDETAIL_ERROR'
